### ISSUE TITLE
Fine Tuning on Custom Dataset

### ISSUE THREAD

**Issue by r12sharma** [ihdia/BoundaryNet#1]
Hello
Our team is working on OCR and layout detection and currently we are doing the bounding box annotations manually. We are looking for an Optimised approach to the aforementioned problem, our document images comprises of densely laid out and multi-class region instances with large range in aspect ratio.

We are primarily working on mixed text(English+Sanskrit) printed document images and are looking to train the model from scratch but could we also use your Pretrained Model to fine tune on our dataset and how effective would the latter approach be ?

**Comment by cvitatma** [comment]
Hi @r12sharma . Could you show some examples of document images you are working with? That will help determine feasibility of our approach. If possible, overlay the bounding boxes so that we know what would be the effective input to BoundaryNet.
